# Generated by Django 3.2.12 on 2023-03-14 19:54

from django.db import migrations, models
import django.db.models.deletion
import udc_rec_sys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('file', models.FileField(upload_to=udc_rec_sys.models.save_article)),
                ('file_name', models.CharField(default='file', max_length=256)),
                ('main_rec_udc', models.CharField(blank=True, default='None', max_length=64)),
                ('other_rec_udc', models.CharField(blank=True, default='None', max_length=256)),
                ('author_udc', models.CharField(blank=True, default='None', max_length=256)),
                ('file_structure', models.CharField(default='None', max_length=1048576)),
                ('onto_math_pro_version', models.CharField(blank=True, max_length=128)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='ArticleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(default='None', max_length=128, unique=True)),
                ('name_en', models.CharField(default='None', max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Статусы статей',
            },
        ),
        migrations.CreateModel(
            name='OntologyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=512)),
                ('domain', models.CharField(blank=True, default='None', max_length=512)),
                ('version', models.CharField(default='None', max_length=128)),
                ('data', models.CharField(default='None', max_length=1048576)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Онтологии',
            },
        ),
        migrations.CreateModel(
            name='ResourceDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=128, unique=True)),
                ('link', models.CharField(default='None', max_length=512, unique=True)),
                ('last_connection', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='ResourceDownloadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(default='None', max_length=128, unique=True)),
                ('name_en', models.CharField(default='None', max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Статусы ресурсов',
            },
        ),
        migrations.CreateModel(
            name='UdcTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udc_code', models.CharField(default='None', max_length=64, unique=True)),
                ('name_ru', models.CharField(blank=True, default='None', max_length=512)),
                ('name_en', models.CharField(blank=True, default='None', max_length=512)),
                ('udc_map', models.CharField(default='None', max_length=1048576)),
                ('exp_class_coefficient', models.CharField(default='None', max_length=4096)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Карты UDC',
            },
        ),
        migrations.CreateModel(
            name='UserStash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='udc_rec_sys.article')),
            ],
            options={
                'verbose_name_plural': 'Загрузки пользователей',
            },
        ),
    ]
