# Generated by Django 3.2.12 on 2023-03-14 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('udc_rec_sys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userstash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcedownload',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='udc_rec_sys.resourcedownloadstatus'),
        ),
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='udc_rec_sys.resourcedownload'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='udc_rec_sys.articlestatus'),
        ),
    ]
